apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: git@github.com:JorellDacasin/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://afa8761a6902d4eed83106ebd15d7aec-1934446345.ap-southeast-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIBmf2zur4hUTanBkQCLIz1syNw+NlUAOfOWG8f8wov0NEqxeCqleCqZeCngKWggBEAEaBgic
      4daWBiIKc3lzY2hhbm5lbCpAZTg3NTJlNzZkYzRiNjliMTMyYjg1ZTVlZGE4NDVkYTc2NTEyNjIx
      NDYwMzA3OWIwMjM3ZWIxZjE4NTQ4NmFlYhIaEhhnRLxwX8J0SsSAkknWSkz430g4Gk0IOzgSqV0K
      pl0So10SmSsKB09yZGVyZXISjSsS0hYKDnN1cHBseWNoYWluTVNQEr8WGssUCgNNU1ASwxQSuBQS
      tRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVSXJZOG9ndlZIVVM0Y08ybDdnTUFTNzRjRTBBd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFNE1UZzFOREkxV2hjTk1qVXdOVEEzTVRnMU5ESTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJLSG82
      RmVHKy85d2tJRGxQSTIvUGZtdHZFek1rcnVEVld0UWZ4bVNTcExuZTVMTkk1TnQKeVVaUjViVDJ6
      dFkzcmhvNnVEZjJIdlNxbGVvS2pVN1dkRDZqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVGNBUFp5NGt3QmFBenFSaENqRWlGbkgv
      K1R1akFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQThZWGhrQnlaN0dITkVHaEJZdEk0Y2NVNTJo
      RXd2Z1dhdG1JWVQ1bDAKSlVjQ0lRQ0NlQUVxczBFK254RzdpbVZvQVNOdG4vWGVvSmF0THdNWThZ
      cmxDVE9rd3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKiCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNFRDQ0FvaWdBd0lCQWdJVUVKTHdCc1lVclpteUhtRm9RNWhiLzBsSDdW
      Z3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTRNVGt3TXpBd1do
      Y05Nak13TnpFNE1Ua3dPREF3V2pCc01Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RNHcKREFZRFZR
      UUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1ZRV1J0YVc1QWMzVndjR3g1WTJoaGFXNHRibVYwTUZr
      dwpFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWxuNEkrWmoxa3FpdzhuMmkzUStqcW1p
      dW1iZnNHUGowCjNIcTVVcVdxWWx3UWVEejB1bUZwZm1sSFk2RVErVnVEQjBDWVB1WExJczB5Qy9i
      VzZuc2ZXS09DQVJRd2dnRVEKTUE0R0ExVWREd0VCL3dRRUF3SUhnREFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUUgxTnVjaU02MgpkbU1yQ0Mzc3hQL2Jtc2VXdXpBZkJnTlZIU01FR0RB
      V2dCVGNBUFp5NGt3QmFBenFSaENqRWlGbkgvK1R1akFrCkJnTlZIUkVFSFRBYmdobGpZUzEwYjI5
      c2N5MDNOVFZtT1dRMVlqZGpMWEIzWTNvNE1JR0pCZ2dxQXdRRkJnY0kKQVFSOWV5SmhkSFJ5Y3lJ
      NmV5SmhZbUZqTG1sdWFYUWlPaUowY25WbElpd2lZV1J0YVc0aU9pSjBjblZsSWl3aQphR1l1UVda
      bWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3
      CmJIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9pWVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBF
      QXdJRFJ3QXcKUkFJZ05HRGhHaWNGUWtUb21hWW9VUG11UDhsS3o3R0JGaFliTTR0RFFPU3AxYzhD
      SUZuQUY1YmFtY1ZUOU5aWQpEbnA5QXdnZEVxYXpHVnppWWVMYkxqR09uSnhxCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkr1BS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQVRDQ0FhYWdBd0lCQWdJVUlyWThvZ3ZWSFVTNGNPMmw3Z01BUzc0Y0UwQXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056RTRNVGcxTkRJMVdoY05NalV3
      TlRBM01UZzFOREkxV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCS0hvNkZlRysvOXdrSURsUEkyL1BmbXR2RXpNa3J1RFZXdFFmeG1TU3BMbmU1TE5J
      NU50CnlVWlI1YlQyenRZM3JobzZ1RGYySHZTcWxlb0tqVTdXZEQ2alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRjQVBaeTRrd0Jh
      QXpxUmhDakVpRm5ILytUdWpBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUE4WVhoa0J5WjdHSE5F
      R2hCWXRJNGNjVTUyaEV3dmdXYXRtSVlUNWwwCkpVY0NJUUNDZUFFcXMwRStueEc3aW1Wb0FTTnRu
      L1hlb0phdEx3TVk4WXJsQ1RPa3d3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoG
      QWRtaW5zKgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1pbnMaHgoMQmF0
      Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25zEggaBkFkbWlu
      cxokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zGooSCg1Db25zZW5zdXNUeXBl
      EvgREu0RCghldGNkcmFmdBLgEQrJEQoYb3JkZXJlcjEuc3VwcGx5Y2hhaW4tbmV0EIo3GtMILS0t
      LS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQXFtZ0F3SUJBZ0lVZGg3Ym9iTlpWUHp0
      em83NGgyN2lnSnhSNVhVd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFO
      QmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQ
      Y21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3
      TnpFNE1Ua3dNekF3V2hjTk1qTXdOekU0TVRrd09EQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIK
      TUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVHhx
      Wi82SEp2T3ltdVBMS0VUZWp0TzkvejYKd0xnMnBXMWFlN3ZadnE5YUJ3aVNhQWZxWHFBOUZTNE1q
      Y2hLQVViMExKMEhyQlI1UXFZaXlySUphQm9FbzRJQgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURB
      Z09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJB
      ZjhFQWpBQU1CMEdBMVVkRGdRV0JCUTZkSnFBc0RCUnJrdXV1aC8xS2pTZEc5aE8Kb0RBZkJnTlZI
      U01FR0RBV2dCVGNBUFp5NGt3QmFBenFSaENqRWlGbkgvK1R1akEvQmdOVkhSRUVPREEyZ2hodgpj
      bVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJH
      OWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdCN0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FX
      RjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NH
      eDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJNkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpq
      MEVBd0lEU0FBd1JRSWhBT1c1YzMxOHhDdmIyTlpYClliUy9DQ0Y3bjdkNDZIbVR3bXNHcnRGNFFR
      ZC9BaUI0eVdtVGZjaFlUQy8yckd5S2cvd1ZzRnM5aVpLaktqeDIKZDhCc3d2bjJFUT09Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KItMILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURB
      ekNDQXFtZ0F3SUJBZ0lVZGg3Ym9iTlpWUHp0em83NGgyN2lnSnhSNVhVd0NnWUlLb1pJemowRUF3
      SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRY
      QndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpFNE1Ua3dNekF3V2hjTk1qTXdOekU0TVRrd09E
      QXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRH
      OXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBdwpEZ1lEVlFRTEV3ZHZjbVJsY21WeU1T
      RXdId1lEVlFRREV4aHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1ClpYUXdXVEFUQmdjcWhr
      ak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVHhxWi82SEp2T3ltdVBMS0VUZWp0TzkvejYKd0xnMnBX
      MWFlN3ZadnE5YUJ3aVNhQWZxWHFBOUZTNE1qY2hLQVViMExKMEhyQlI1UXFZaXlySUphQm9FbzRJ
      QgpNRENDQVN3d0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndN
      QkJnZ3JCZ0VGCkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUTZkSnFBc0RC
      UnJrdXV1aC8xS2pTZEc5aE8Kb0RBZkJnTlZIU01FR0RBV2dCVGNBUFp5NGt3QmFBenFSaENqRWlG
      bkgvK1R1akEvQmdOVkhSRUVPREEyZ2hodgpjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhT
      Q0dtOXlaR1Z5WlhJeExtUmxkbVZzYjNBdWJHOWpZV3d1ClkyOXRNR3dHQ0NvREJBVUdCd2dCQkdC
      N0ltRjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldW
      dWRFbEVJam9pYjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdQpWSGx3WlNJ
      NkltOXlaR1Z5WlhJaWZYMHdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBT1c1YzMxOHhDdmIyTlpY
      ClliUy9DQ0Y3bjdkNDZIbVR3bXNHcnRGNFFRZC9BaUI0eVdtVGZjaFlUQy8yckd5S2cvd1ZzRnM5
      aVpLaktqeDIKZDhCc3d2bjJFUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1z
      EAoYASAFKICAgAgaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5z
      KgZBZG1pbnMSwy8KC0NvbnNvcnRpdW1zErMvEuguChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0Szi4S
      uxcKD21hbnVmYWN0dXJlck1TUBKnFxqvFQoDTVNQEqcVEpwVEpkVCg9tYW51ZmFjdHVyZXJNU1AS
      hgYtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0RUQ0NBYktnQXdJQkFnSVVXL25WWXdp
      ZDdZcmNNUTFXUE5uNkFSb0FWcVF3Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBn
      eER6QU5CZ05WQkFnTUJscDFjbWxqYURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFR
      S0RBeE5ZVzUxWm1GamRIVnlaWEl4SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kx
      dVpYUXdIaGNOTWpJd056RTRNVGcxTmpJNVdoY05NalV3TlRBM01UZzFOakk1V2pCa01Rc3dDUVlE
      VlFRRwpFd0pEU0RFUE1BMEdBMVVFQ0F3R1duVnlhV05vTVE4d0RRWURWUVFIREFaYWRYSnBZMmd4
      RlRBVEJnTlZCQW9NCkRFMWhiblZtWVdOMGRYSmxjakVjTUJvR0ExVUVBd3dUWTJFdWJXRnVkV1po
      WTNSMWNtVnlMVzVsZERCWk1CTUcKQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJNUy9nVHZ2
      M0pmc0cwSE9vNWVKM1pIMlM3dDh1aVp3bHNoLwo3dUN4VWZnVi9Ydk9IRGpXaXlPU091TVdDdTcz
      Zk9pWFpGYXBXa0wySTQ5eUlIZ1ZzRTZqUWpCQU1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEZ1lE
      VlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUzFyNEl3TGRnbjNjVloKeWFYSDJpM01MQTdW
      cGpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQSszdno4V0tmV3VkZTVtWVlwWVdPS2VQVgptWCto
      Qk0vQ2VkYTVmYnlsU2p3Q0lRREl6MXpNS3plR2JlbDVBc3AyYUNiTFg4S21IMTZvS2ZzSkIwd3A0
      RCttCllnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi4wgtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJREVEQ0NBcmVnQXdJQkFnSVVNVi9jT3o1RUZSbjR6TmVqYTlZS01YTko4R1F3
      Q2dZSUtvWkl6ajBFQXdJdwpaREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1SVXdFd1lEVlFRS0RBeE5ZVzUxWm1GamRIVnlaWEl4
      SERBYUJnTlZCQU1NRTJOaExtMWhiblZtWVdOMGRYSmwKY2kxdVpYUXdIaGNOTWpJd056RTRNVGt3
      TkRBd1doY05Nak13TnpFNE1Ua3dPVEF3V2pDQmhqRUxNQWtHQTFVRQpCaE1DUTBneEdqQVlCZ05W
      QkFjVEVUUTNMak00THpndU5UUXZXblZ5YVdOb01SVXdFd1lEVlFRS0V3eE5ZVzUxClptRmpkSFZ5
      WlhJeEl6QU1CZ05WQkFzVEJXRmtiV2x1TUJNR0ExVUVDeE1NYldGdWRXWmhZM1IxY21WeU1SOHcK
      SFFZRFZRUUREQlpCWkcxcGJrQnRZVzUxWm1GamRIVnlaWEl0Ym1WME1Ga3dFd1lIS29aSXpqMENB
      UVlJS29aSQp6ajBEQVFjRFFnQUVPbDFvZlB5dXcxbXJQZ1dMUFN1OVEyN3d1UWswbFg4c2hicFdR
      TGtHNHFZeGhrdVdQQjNLCjBXTnVXTWdQTnNib2w4bzJndTg2TWZGV0NNeWw0eTN6NktPQ0FTSXdn
      Z0VlTUE0R0ExVWREd0VCL3dRRUF3SUgKZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdC
      QlJWeFdTMTlrM2hNbzNtSjdubzdHckxveHlrRERBZgpCZ05WSFNNRUdEQVdnQlMxcjRJd0xkZ24z
      Y1ZaeWFYSDJpM01MQTdWcGpBa0JnTlZIUkVFSFRBYmdobGpZUzEwCmIyOXNjeTAyWkdRNU5tUm1O
      V0kwTFRSd1kySjRNSUdYQmdncUF3UUZCZ2NJQVFTQmluc2lZWFIwY25NaU9uc2kKWVdKaFl5NXBi
      bWwwSWpvaWRISjFaU0lzSW1Ga2JXbHVJam9pZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dQpJ
      am9pYldGdWRXWmhZM1IxY21WeUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWJX
      RnVkV1poClkzUjFjbVZ5TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUpoWkcxcGJpSjlmVEFLQmdncWhr
      ak9QUVFEQWdOSEFEQkUKQWlCUUNlcmtQVXNYRWZNb2xCelNGTXprM1h3ZlVadklwMW0xN3lKSlRu
      V2wxQUlnUXZ6aDZza3l0eHZIS2thKwpwNko2S3VPYXlvNDNmcEd6djhqNE94Tk9mUzA9Ci0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkqGBi0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDRFRDQ0FiS2dBd0lCQWdJVVcvblZZd2lkN1lyY01RMVdQTm42QVJvQVZx
      UXdDZ1lJS29aSXpqMEVBd0l3ClpERUxNQWtHQTFVRUJoTUNRMGd4RHpBTkJnTlZCQWdNQmxwMWNt
      bGphREVQTUEwR0ExVUVCd3dHV25WeWFXTm8KTVJVd0V3WURWUVFLREF4TllXNTFabUZqZEhWeVpY
      SXhIREFhQmdOVkJBTU1FMk5oTG0xaGJuVm1ZV04wZFhKbApjaTF1WlhRd0hoY05Nakl3TnpFNE1U
      ZzFOakk1V2hjTk1qVXdOVEEzTVRnMU5qSTVXakJrTVFzd0NRWURWUVFHCkV3SkRTREVQTUEwR0Ex
      VUVDQXdHV25WeWFXTm9NUTh3RFFZRFZRUUhEQVphZFhKcFkyZ3hGVEFUQmdOVkJBb00KREUxaGJu
      Vm1ZV04wZFhKbGNqRWNNQm9HQTFVRUF3d1RZMkV1YldGdWRXWmhZM1IxY21WeUxXNWxkREJaTUJN
      RwpCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk1TL2dUdnYzSmZzRzBIT281ZUozWkgyUzd0
      OHVpWndsc2gvCjd1Q3hVZmdWL1h2T0hEaldpeU9TT3VNV0N1NzNmT2lYWkZhcFdrTDJJNDl5SUhn
      VnNFNmpRakJBTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIw
      R0ExVWREZ1FXQkJTMXI0SXdMZGduM2NWWgp5YVhIMmkzTUxBN1ZwakFLQmdncWhrak9QUVFEQWdO
      SkFEQkdBaUVBKzN2ejhXS2ZXdWRlNW1ZWXBZV09LZVBWCm1YK2hCTS9DZWRhNWZieWxTandDSVFE
      SXoxek1LemVHYmVsNUFzcDJhQ2JMWDhLbUgxNm9LZnNKQjB3cDREK20KWWc9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjwKC0VuZG9yc2VtZW50Ei0SIwgBEh8SCBIGCAESAggA
      GhMSEQoPbWFudWZhY3R1cmVyTVNQGgZBZG1pbnMiOAoHUmVhZGVycxItEiMIARIfEggSBggBEgII
      ABoTEhEKD21hbnVmYWN0dXJlck1TUBoGQWRtaW5zIjgKB1dyaXRlcnMSLRIjCAESHxIIEgYIARIC
      CAAaExIRCg9tYW51ZmFjdHVyZXJNU1AaBkFkbWlucyI5CgZBZG1pbnMSLxIlCAESIRIIEgYIARIC
      CAAaFRITCg9tYW51ZmFjdHVyZXJNU1AQARoGQWRtaW5zKgZBZG1pbnMSshYKCmNhcnJpZXJNU1AS
      oxYavxQKA01TUBK3FBKsFBKpFAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCK1RDQ0FaNmdBd0lCQWdJVVVQRDBLK29XcXIwa20xY2V4OFhCVUZELzl3d3dDZ1lJ
      S29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFE
      REE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNakEzTVRneE9EVTRNemxhRncweU5UQTFNRGN4
      T0RVNE16bGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFO
      QmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dP
      WTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNw
      Z0E2K0JVWUwybmdjcU1SdFg2c2Z4Q3pudTM5NkM1dzZzRS92L2xRNlJMT3d3c3BTKzlPbFloeUd6
      bkV2Cll5ZHZaREQ3MGdmWDkzSWtDdXdUOXNveG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9N
      QTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVWnFJQ085K212MXFTUThhMmhhL1gr
      Y3dWSHNvd0NnWUlLb1pJemowRQpBd0lEU1FBd1JnSWhBSjRJYUo1VUd4R3JlNXBkSkRnRng1eXY0
      S29mb3ZSUjhyeXZoNGRZZ3ZXNkFpRUEzODFjCjlIK1A3K1BMN0tBNjBJa29STlFmekNQZEJyWExG
      ODJMc2NzWGEzND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQzdUQ0NBcFNnQXdJQkFnSVVUTmhIR2hvMDBSVTVuVlpwYmROVGJ3a0sr
      Smt3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dG
      UVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTWpBM01UZ3hPVEEyTURCYUZ3MHlN
      ekEzTVRneE9URXhNREJhTUhneEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFN
      Qzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEhqQU1CZ05WCkJBc1RC
      V0ZrYldsdU1BNEdBMVVFQ3hNSFkyRnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNt
      bGwKY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUXVER0c3cHpDb2o1
      cnhmKzRPaks3MApUYU9EbHB5NFFCWGFXL2hJMjBBKzJ2VllXVWJrU21hd05uWTR0c0s5cjNNTWhr
      SG9UTSszUS9YQUJQOFBZaHVJCm80SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0Ex
      VWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUUKRkh3R1AzSHlzanpJdjFYdW83TG1tU3lIVEJZNE1C
      OEdBMVVkSXdRWU1CYUFGR2FpQWp2ZnByOWFra1BHdG9XdgoxL25NRlI3S01DUUdBMVVkRVFRZE1C
      dUNHV05oTFhSdmIyeHpMVFZtT0Roa05UVm1PVGN0Ym0xeE9Yb3dnWTBHCkNDb0RCQVVHQndnQkJJ
      R0FleUpoZEhSeWN5STZleUpoWW1GakxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNu
      VmxJaXdpYUdZdVFXWm1hV3hwWVhScGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldW
      dQpkRWxFSWpvaVFXUnRhVzVBWTJGeWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0
      aWZYMHdDZ1lJCktvWkl6ajBFQXdJRFJ3QXdSQUlnUDhsazk0Q0NQMzNZcUJEZGxrTCtVbGNNeURE
      MTRlYmZKVFptdlo5NW01RUMKSUY1KzNCSkluVkJYS3ZEaS9xNGIxeU00NjM0ZTh1QmNEMm1UajZX
      ZmdwYlkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1C
      RUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrVENDQVo2Z0F3SUJBZ0lVVVBEMEsrb1dxcjBrbTFj
      ZXg4WEJVRkQvOXd3d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdO
      VkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhK
      eWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1qQTNNVGd4T0RV
      NE16bGFGdzB5TlRBMU1EY3hPRFU0TXpsYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFEyRnljbWxs
      Y2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dx
      aGtqT1BRTUJCd05DCkFBU3BnQTYrQlVZTDJuZ2NxTVJ0WDZzZnhDem51Mzk2QzV3NnNFL3YvbFE2
      UkxPd3dzcFMrOU9sWWh5R3puRXYKWXlkdlpERDcwZ2ZYOTNJa0N1d1Q5c294bzBJd1FEQVBCZ05W
      SFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVacUlD
      TzkrbXYxcVNROGEyaGEvWCtjd1ZIc293Q2dZSUtvWkl6ajBFCkF3SURTUUF3UmdJaEFKNElhSjVV
      R3hHcmU1cGRKRGdGeDV5djRLb2ZvdlJSOHJ5dmg0ZFlndlc2QWlFQTM4MWMKOUgrUDcrUEw3S0E2
      MElrb1JOUWZ6Q1BkQnJYTEY4MkxzY3NYYTM0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoG
      QWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoG
      QWRtaW5zIjMKB1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1p
      bnMiMwoHV3JpdGVycxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0
      CgZBZG1pbnMSKhIgCAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyoGQWRt
      aW5zGkAKFUNoYW5uZWxDcmVhdGlvblBvbGljeRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09y
      ZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBIC
      EgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBI
      YXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0
      cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpOChBPcmRlcmVyQWRkcmVzc2VzEjoSHwodb3JkZXJl
      cjEuc3VwcGx5Y2hhaW4tbmV0OjcwNTAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFi
      aWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJz
      GgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgS
      DggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
